[package]
name = "client"
version = "0.1.0"
authors = ["Liam Perlaki <lperlaki@icloud.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
stdweb = "0.4.13"
yew = { git = "https://github.com/DenisKolodin/yew" }
