[package]
name = "rocket-yew"
version = "0.1.0"
authors = ["Liam Perlaki <lperlaki@icloud.com>"]
edition = "2018"


[dependencies]
common = { path = "../common" }
rocket = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "serve"]
