[package]
name = "common"
version = "0.1.0"
authors = ["Liam Perlaki <lperlaki@icloud.com>"]
edition = "2018"

[dependencies]
serde = { version = '1.0.84', features = ['derive'] }
serde_json = "1.0.34"